# Generated by Django 5.1.4 on 2024-12-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worddocument',
            options={'ordering': ['-page_count']},
        ),
        migrations.RenameField(
            model_name='worddocument',
            old_name='name',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='worddocument',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='worddocument',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='worddocument',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worddocument',
            name='creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worddocument',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='worddocument',
            name='file_path',
            field=models.CharField(default=str, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worddocument',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worddocument',
            name='modification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worddocument',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worddocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
