# Generated by Django 5.1.4 on 2024-12-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_filerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFile',
        ),
        migrations.DeleteModel(
            name='WordDocument',
        ),
        migrations.AddField(
            model_name='filerecord',
            name='sheet_names',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
