# Generated by Django 5.1.4 on 2024-12-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_imagefile_delete_worddocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='sheet_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
