# Generated by Django 5.1.4 on 2024-12-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_filerecord_sheet_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='sheet_names',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
